// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8m4gzdy4tv9TjO8aUHfumTFuAMVueF28',
    appId: '1:925800864876:web:881469c6b3ea4175d8cc49',
    messagingSenderId: '925800864876',
    projectId: 'campus-management-system-4962b',
    authDomain: 'campus-management-system-4962b.firebaseapp.com',
    storageBucket: 'campus-management-system-4962b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkCunczOo4MJS4oN4dBan-7cY1bHhxkI4',
    appId: '1:925800864876:android:694fef18678655bed8cc49',
    messagingSenderId: '925800864876',
    projectId: 'campus-management-system-4962b',
    storageBucket: 'campus-management-system-4962b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7WbcWWp7f0v6QKc8w6wIrMciqnkLX9dQ',
    appId: '1:925800864876:ios:a36dc16ea687f949d8cc49',
    messagingSenderId: '925800864876',
    projectId: 'campus-management-system-4962b',
    storageBucket: 'campus-management-system-4962b.appspot.com',
    iosClientId: '925800864876-9c71uqgt67g235688o5vcb5f4dhh2iaj.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7WbcWWp7f0v6QKc8w6wIrMciqnkLX9dQ',
    appId: '1:925800864876:ios:c5d1c6b134a211e9d8cc49',
    messagingSenderId: '925800864876',
    projectId: 'campus-management-system-4962b',
    storageBucket: 'campus-management-system-4962b.appspot.com',
    iosClientId: '925800864876-f2fqpom6fpi96kkqv5v5bkhu9najnejv.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusManagementSystem.RunnerTests',
  );
}
