name: campus_management_system
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'



dependencies:
  flutter:
    sdk: flutter
# Firebase Database
  cloud_firestore: ^4.7.1
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  google_fonts: ^4.0.4
  sliding_switch: ^1.1.0
  go_router: ^7.0.1
  firebase_database: ^10.2.1
  provider: ^6.0.5
  intl: ^0.17.0
  introduction_screen: ^3.1.8
  curved_navigation_bar: ^1.0.3
  qr_flutter: ^4.1.0
  booking_calendar: ^1.1.9
  camera: ^0.10.5+2
  flutter_staggered_grid_view: ^0.4.0
  qr_code_scanner: ^1.0.1
  uuid: ^3.0.7
  firebase_storage: ^11.2.5
  flutter_background_service: ^3.0.1
  fl_chart: ^0.63.0
  url_launcher: ^6.0.0
  http: ^0.13.3
  path_provider: ^2.0.5
  dio: ^4.0.4
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "lib/images/play_store_512.png"


  


flutter:
  uses-material-design: true

  assets:
   - lib/images/
